### ISSUE TITLE
[7534, 8339, 9931, 10389, 9117, 9458] ConnectBooster PDF rendering inside Desktop Portal

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#1]
ConnectBooster PDF not displayed inside desktop portal because issues with electron client. It need special care with that case.

Web version of portal functional as expected.

**Comment by Nness** [comment]
We will working on this issue at start of next month.

**Comment by chris-ls** [comment]
This issue is fixed inside Desktop/v1.72
