### ISSUE TITLE
Logo on login form is stretched on Firefox

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#10]
Firefox:
![image](https://user-images.githubusercontent.com/10571313/41518209-052418f6-7315-11e8-9588-3aefbf672a80.png)

Chrome:
![image](https://user-images.githubusercontent.com/10571313/41518215-11bdbcd4-7315-11e8-84d0-d2de597ce600.png)

**Comment by chris-ls** [comment]
This is fixed with Web/v2.18.8 released on 20th June 2018.
