### ISSUE TITLE
[19009, 21848] Desktop client doesn't handle expiring authentication after 30 days

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#106]
When Portal users log in, they receive an authentication cookie which lasts 30 days.
After this 30 days, they are required to log in again.

If the Portal launches itself just before the cookie expiration time, then it is possible that the cookie will expire while the user is using the application.
This can result in unexpected and hard to diagnose behavior:
e.g. Unable to submit a ticket

**Comment by DDAndyChen** [comment]
Currently the expiring time has been reduced to 10 days, this issue needs to be addressed more urgently.

The expire time will be changed back to 30 days in the next server release.

**Comment by Nness** [comment]
This is now handled.
