### ISSUE TITLE
[19252] Chat history list doesn't initially populate correctly inside DD Tech

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#108]
When navigating to the "Chat History" tab inside DD Tech, no chat histories show up, even if they do exist.

It looks like this issue is related to how DD Tech is handling the data it is fetching from the Server.
The historical chat history data is there and is being returned, but just not displayed.

As a "workaround", chat histories will show up if you apply a specific company filter and click "Apply".

**Comment by Andrew-Lahikainen** [comment]
This can happen when the creator of a session is deleted from ConnectWise. The front end code breaks and this results in the list not being displayed. Proposed fix will be to send down a fake contact record, something like "Unknown".

**Comment by Andrew-Lahikainen** [comment]
This has been fixed and deployed (1.16.5)
