### ISSUE TITLE
[9562] Fix IE11 bugs and freeze development of an IE11 only Portal

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#11]
We will be creating an IE11 only version of the Portal which will be served up to users that are on IE11. Development will be frozen and will be restricted to critical bug fixes and security fixes.

The IE11 version will not support Dd Talk, but will have the new request support UI.

**Comment by chris-ls** [comment]
We will be waiting until the new Request Support UI and the new Chat System is fully released before proceeding with this.

**Comment by chris-ls** [comment]
This issue needs to be looked at again.
At this point in time, the new support UI and new chat system have been in production for many months.

Do we choose to lock in the given functionality here?

I believe that IE 11 detection is already built into the index.html. It just needs an alternative handling wired up to deliver an IE 11 build.

**Comment by Nness** [comment]
This has been fixed on server 18.115.1. Expected release and deploy date to be on 14th of April.

Portal on IE 11 will lock down to version 3.9.3 which was released around mid of 2019. No change or fix will be apply to that version. It is what it is until it is dead by DeskDirector API deprecation.
