### ISSUE TITLE
[19468] Take Screenshot button doesn't work in TicketsV2 on Desktop Client

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#112]
![image](https://user-images.githubusercontent.com/5317900/63558208-176d7780-c5a0-11e9-95f7-2421546f674c.png)

The "Take a Screenshot" button is not working correctly inside v2.6 of the Desktop Client.

This has been fixed in the latest Web Client version, but is awaiting deploy to Desktop.

This fix will come with the first release of v3.x of the Desktop Client.
ETA: Mid September

**Comment by 4rsl** [comment]
Thanks for taking care of this guys!

**Comment by Andrew-Lahikainen** [comment]
Shipped beginning of this week 🥳
