### ISSUE TITLE
[19384] Tech: "send to" checkboxes get switched back on after being switched off

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#114]
This happens because the "send to" local state is being reset by the board's default "send to" options.

**Comment by Lowell-Syncrety** [comment]
Is there a way then to not have the checkboxes be reset to whatever the initial default may be?

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety will be prioritising this bug, hoping to fix this week

**Comment by Andrew-Lahikainen** [comment]
This has been fixed and released.

@Lowell-Syncrety have a go and let me know if any issues

**Comment by Lowell-Syncrety** [comment]
Thanks @Andrew-Lahikainen ... btw, thanks for how responsive you folks are with support, how open you are with these 2 lists on Github, and the development you're doing. I rave about DeskDirector on many IT MSP groups.

**Comment by Andrew-Lahikainen** [comment]
And thank you @Lowell-Syncrety for all the awesome feedback you've been giving us! I personally find it really motivating to interact directly with the people who are using the software we write. So thanks again 😃
