### ISSUE TITLE
[19558] Form to use boarder on text field (UX)

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#117]
To use boarder on text field include short text field and long text field. 

For long text field,  give default of 2~3 rows, to make sure it is obvious.

**Comment by chris-ls** [comment]
We can use the same type of input design used in our standard request types.
These have borders for both single line input and textarea.

It will likely change the look and feel of DD Forms a lot.
The form elements may need adjustments to paddings & margins.

**Comment by Nness** [comment]
This is done.
