### ISSUE TITLE
Portal attachment overlay

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#123]
Last week, Chris did attachment overlay. The UI is not looking as great as following image. It was similar as ticket detail v1, attachment as block. Before it is released, we should take look at it, see if we can reverse back if possible. (Keep the overlay)

![2019-09-10_14h38_13](https://user-images.githubusercontent.com/1712143/64579950-be437780-d3d8-11e9-8196-e945c8b6347f.png)

**Comment by Andrew-Lahikainen** [comment]
@Nness I think this is done in tickets-v2 right?
