### ISSUE TITLE
[20245] Learning item is missing descriptions and version

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#126]
Description and version should be displayed within learning items.

![image](https://user-images.githubusercontent.com/1712143/65200990-064f5200-dadd-11e9-9591-d7955b85405f.png)
![image](https://user-images.githubusercontent.com/1712143/65200994-094a4280-dadd-11e9-82ca-e7ae6edc770a.png)

**Comment by Nness** [comment]
The model for learning page does include description and version. Portal is not displaying.

**Comment by Lowell-Syncrety** [comment]
Thanks! I know I used to see it there but can't recall how long ago that was. We're using V2 portal.

**Comment by Nness** [comment]
Ever since v2 I believe. Since there was implementation for OneNote integration, thus, the portal maintainer might try to keep both implementation looks same, thus removed description and version display from learning.

**Comment by Lowell-Syncrety** [comment]
Just testing out the new menu system... it too doesn't show the description. Is it supposed to?

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety I'll be rolling out a release probably this week that will show descriptions if they exist

**Comment by Lowell-Syncrety** [comment]
> @Lowell-Syncrety I'll be rolling out a release probably this week that will show descriptions if they exist

Thanks much!

**Comment by Andrew-Lahikainen** [comment]
Fixed and released in Portal 3.6.5
