### ISSUE TITLE
[20260] PDF link inside wufoo form does not open inside chrome (firefox works fine)

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#127]
Currently, we have sandbox setting for wufoo form inside our portal. Sandbox setting is `allow-forms allow-scripts allow-same-origin allow-popups`.

If there is PDF link that will open up inside new tab, chrome will render blank page instead. This is caused by sandbox still applied to popup.

We should add following attribute to sandbox to allow popup to escape sandbox.

The sandbox setting should setup to `allow-forms allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox`. This has been tested locally.

**Comment by Andrew-Lahikainen** [comment]
Fixed and released in Portal 3.6.5
