### ISSUE TITLE
Web portal chat room indicator display when it shouldn't

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#128]
User info API result has following permission result.
```
permission
    - chat: false
setting
    - enableChat: true
    - useChatV4: false
```
User does not have any chat session going.

The problem is with legacy chat version, where chat room session icon at top navigation bar is displayed even when chat session count is zero.

When switch to chat v4, chat bubble on navbar will no longer be there.

![2019-09-24_08h37_27](https://user-images.githubusercontent.com/1712143/65460688-9529e900-dea6-11e9-951e-cd9237d8dc7d.png)

**Comment by Andrew-Lahikainen** [comment]
Fixed and released in Portal 3.6.5
