### ISSUE TITLE
[21136,21385,20295,21366] Uninstall portal desktop's CLI app

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#129]
A CLI app to go through uninstall registry to remove DeskDirector portals. 
* Remove from app install history (add or remove apps)
* Remove from file system, include files inside app data
* Remove shortcut from desktop
* Generate report on what has been removed

**Comment by RyanScottT** [comment]
Will this also uninstall previous versions of DD Portal such as the .MSI installs?

**Comment by Nness** [comment]
It will try to uninstall all the DD portal that's been installed on given machine.

**Comment by Nness** [comment]
Ticket 21385 and 20295 both provided useful information regarding the uninstall issue.

**Comment by Nness** [comment]
Ticket 21366 provide scenario where `update.exe` could throw exception during uninstallation. It is cause by not handle registry not exist scenario.

Customer also mentioned that shortcut is not removed after uninstall.

**Comment by DDAndyChen** [comment]
New tool to remove existing installed desktop portals: https://help.deskdirector.com/article/huqqqba1r0-ddportal-removal-tool-uninstalling-windows-portals
