### ISSUE TITLE
[20595] Improve search for special characters

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#136]
Improve the way we match special characters and try to remove accents from certain characters.

Example search string: St'át'imc

**Comment by Nness** [comment]
New behavior on search term is to allow '*' post wild card. Also respect some of special characters.

e.g. `St'*` will return `St'am` whre `St*` also works. It will be inside server 18.97.1 release. Scheduled on 4th of Nov
