### ISSUE TITLE
[20887] Chat sessions are appearing in the chat session manager when they should not be

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#148]
This happens on the find api:

`POST /api/v2/tech/chat/sessions/find`

**Comment by Nness** [comment]
@Andrew-Lahikainen The intention was let TECH to decide what to do with it. So every find result need to be combine with bulk get tickets results. Either display it and make it gray out, or not display it.

If server do that, the consequence have two fold, depends on implementation. 
Let's use skip 0 and take 20 as example.

1. Member cannot access all sessions, server return empty list. TECH sees empty list auto goes to next page. 
Problem with this approach is if TECH does not do that, user will think there is no more page there.

2. Member cannot access all sessions, server goes to next page until find a list of sections user can access. The response contain request as skip 100 take 20. That means we could already skipped 5 pages.
Problem with this approach is if TECH does not recognize the instruction from the response, next page is skip 20 take 20, then TECH will display exactly same result.

-----------------------
Now if we account for breaking change or move API to next version we could use infinite scroll kind of design. Or delta query. That means it will give a next page query token.

----------------------
Let's face it, chat data have permission itself is problematic. Especially it stored in separate data store. Also even when stored within same store, there are still requirement on joined index.

Another solution is give global chat session list only to admin. Where they are supposed to see all tickets. Then for normal engineer they can see chat session in a specific ticket.

**Comment by Andrew-Lahikainen** [comment]
That makes sense, I'll probably hide the chat history page to non admin
(the chat histories are already on tickets anyway) and then filter out
results for use in the chat manager.

**Comment by Nness** [comment]
Sorry wake you up on your holiday. :(

For detail we can discuss tomorrow.

**Comment by Nness** [comment]
Session should now have meta and with property to indicate whether given technician can access to this session or not.

**Comment by Nness** [comment]
This is now included in server 18.101.1

```javascript
meta?: {
    canAccess: boolean
}
```

**Comment by Andrew-Lahikainen** [comment]
Reopening since front end has not been completed

**Comment by Nness** [comment]
This has been fixed in frontend.
