### ISSUE TITLE
BiggerBrains Video Scale on Installed Client

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/Issues#160]
Videos display fine on Web Portal.
Examples below, all Bigger Brain videos load to be ~150px in height.
Full screen option

Version: 3.3.0 TS

![image](https://user-images.githubusercontent.com/30588784/73795774-93cade80-47ff-11ea-9b20-92a46b079d80.png)

**Comment by DDAndyChen** [comment]
Hi Aycorn,
Please contact support@deskdirector.com to report an issue.
This issue will be closed automatically.
Regards,
Deskdirector

**Comment by Nness** [comment]
rude :P . anyway. I'm working on this issue at moment, hopefully portal release today.

**Comment by Nness** [comment]
This has been fixed on portal version 3.10.0. Which is released on 5th of Feb 2020. It is confirmed working.

End user should expect portal to be updated after windows restart or use `View` => `Reload` inside portal application.
