### ISSUE TITLE
Typo under Office 365 Mail

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/Issues#161]
![image](https://user-images.githubusercontent.com/30588784/73895489-e4ac0700-48d3-11ea-8c63-f3223df00fb7.png)

admin/v2/system/emails/delivery/microsoft

**Comment by DDAndyChen** [comment]
Hi Aycorn,
Please contact support@deskdirector.com to report an issue.
This issue will be closed automatically.
Regards,
Deskdirector
