### ISSUE TITLE
Portal add additional approval related deeplink action support

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#170]
Currently, deep link only supports prompt `approve` action modal. We should support 3 more scenarios.

1. `decline`: prompt decline action modal
2. `excute-approve`: Execute approve action when landed on ticket detail
3. `execute-decline`: Execute decline action when landed on ticket detail.

Name of action can be improved, feel free to give suggestion. The ideal would be `prompt-approve`, but since we already settle on `approve`, I don't want to change existing behaviour. Thus, we need good name for execution.

**Comment by Andrew-Lahikainen** [comment]
@Nness so these execute actions will skip the dialog that pops up asking for a reason?

**Comment by Nness** [comment]
yea. no reason is required for those execute action.. Server will populate system message if not exist. I believe.

**Comment by Andrew-Lahikainen** [comment]
This has been implemented and is awaiting deployment

**Comment by Andrew-Lahikainen** [comment]
deployed
