### ISSUE TITLE
Improve ticket timeline and decrease attachment noise even more.

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#172]
The new ticket detail already improved the situation a lot. The attachment is more subtle than before.

We want to improve it even more. Eventually similar as GitHub. Such as screenshot below
![firefox_pSKa0xgB99](https://user-images.githubusercontent.com/1712143/76794451-ec908c80-682b-11ea-8de1-890f1e53dbab.png)

* Split note have gap in between
* Attachment should be subtle line, instead of a note card or block
* Use line to increase connectivity between note and attachment.

**Comment by Nness** [comment]
Existing interface. Attachment is subtle, the problem is:

* it is hard to figure out association. Or in other word, even though it feels like it has association, but it does not have. It feels like connected with top note, but it might not have any association.
* It feels like part of conversation.
* The whole thing is hard to have visual split and boundary. It take time to split single note away from other note.

![firefox_fLLF3PyWPa](https://user-images.githubusercontent.com/1712143/76794849-ce775c00-682c-11ea-94a7-c5b19faad94c.png)

**Comment by Nness** [comment]
Some of worst scenarios of existing setup.

All the attachment was from single email but the take up tons of space. 

![firefox_PTB3BxP8lJ](https://user-images.githubusercontent.com/1712143/76795167-6f661700-682d-11ea-9820-476d567fe3f4.png)

**Comment by CharlesWarwick** [comment]
One option could be to have a separate 'attachment' timeline
We just show that an attachment arrived and have small, clickable icon that shows the attachment timeline in a different Tab or pops a modal ?

**Comment by Nness** [comment]
Before consider other options, what's the issue with the propose I have made? Is it too hard to achieve? Or looks bad?

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/86202663-ff4e8780-bbb6-11ea-8767-510662b4ca9f.png)

This improvement has been released.
