### ISSUE TITLE
Support ConnectWise's portal link redirect

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#177]
In ConnectWise manager, you can specify portal link, but the deep link is automatically generated by ConnectWise. It is unmatch to DeskDirector deeplink.

https://xxx.deskdirector.com/?company=training&goto=605685

Server side can recognize and translate to portal deep link.

**Comment by GDRBrian** [comment]
Was this implemented?

**Comment by Nness** [comment]
@GDRBrian  It is implement at server side. Server version 18.116

It should be available to AUS on 22nd of April and rest of world 27th of April.
