### ISSUE TITLE
Portal ticket UI v1 is not respecting the 'canFlag' flag

### ISSUE THREAD

**Issue by DDAndyChen** [DeskDirector/Issues#183]
Expect the flag button to be disabled or hidden.
![image](https://user-images.githubusercontent.com/24575499/79190410-5aa29080-7e78-11ea-97e0-f414ee35346a.png)

**Comment by Nness** [comment]
Are you sure you have deployed to dev server? Also, there is no `isProject` flag
![firefox_AjDe0ikX74](https://user-images.githubusercontent.com/1712143/79191612-1b297380-7e7b-11ea-8a8a-1c14532a6ad8.png)

**Comment by Nness** [comment]
Looks fine on ticket detail v2
![image](https://user-images.githubusercontent.com/1712143/79202495-cf33fa00-7e8d-11ea-8d12-612d10b7c5f5.png)

**Comment by Nness** [comment]
Fixed in DeskDirector/portal@2d0f2bb726718c08bed2db1413d71edf2f869536
