### ISSUE TITLE
Upgrade electron version for desktop portal

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#186]
Currently desktop portal is still using electron v2.0. We need to arrange a time to upgrade it.

- [x] Upgrade electron to latest
- [x] Fix PDF rendering issue. Since PDF render support been removed from electron since electron 3.0. We need to use pdf.js for that
- [x] Fix anything that's breaking during upgrade.

The reason locking us from upgrade is PDF engine.

**Comment by big-jw** [comment]
This is affecting us too due to sites which have made changes to accomodate changes to the samesite cookie behaviour https://www.chromium.org/updates/same-site 

For example My Glue no longer works, the logon page just reloads on login.

**Comment by cdandrea** [comment]
I guess we can add ourselves to the list. We're using ChatAssist as an Extension Menu for the DD portal and it behaves fine within a full browser, but not the desktop app itself. I opened a ticket on this and @Nness (Jason) already confirmed exactly the above so we'll sit tight waiting for an ETA. It seems there is a little extra work involved but we're hopeful this can get sorted soon.

It looks like Electron **just** pushed out the samesite property a few weeks ago, [Electron 10.0.0](https://www.electronjs.org/releases/stable?#10.0.0), so the DD team may have had their hands tied regardless. Crossing fingers...

**Comment by big-jw** [comment]
We’ve just admitted defeat and removed our extension menus completely, can’t do anything until Electron is upgraded

Sent from my iPhone

Josh Walton, Service Desk Technician
Have you read our latest news and insights? Click here
Email: josh.walton@itsol.net
Telephone: 01924383250
Mobile:  447474276486
9 The Office Campus, Paragon Business Park, Wakefield, WF1 2UY.
ITSOL Managed Services Ltd is registered in England. Registered number: 09983126. Registered office address: 62-63 Westborough, Scarborough, North Yorkshire, YO11 1TS.
Disclaimer:
 This message contains confidential information and is intended only for reply@reply.github.com. If you are not reply@reply.github.com you should not disseminate, distribute or copy this e-mail. Please notify josh.walton@itsol.net immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. ITSOL Managed Services Ltd therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

On 14 Sep 2020, at 16:44, cdandrea <notifications@github.com> wrote:

﻿

I guess we can add ourselves to the list. We're using ChatAssist as an Extension Menu for the DD portal and it behaves fine within a full browser, but not the desktop app itself. I opened a ticket on this and @Nness<https://github.com/Nness> (Jason) already confirmed exactly the above so we'll sit tight waiting for an ETA. It seems there is a little extra work involved but we're hopeful this can get sorted soon.

**Comment by Nness** [comment]
After discussion with head of company yesterday, I have been assigned to this task. I will look into this within next week or two. 

I will keep this updated.

`SameSite` been supported by electron since 2018~2019. Electron 10.0.0 is enforce `SameSite`. We are unable to upgrade Electron 2.0 to any version higher because of PDF support. This only been resolved from Electron 9.0.0. Which was released May of 2020.

**Comment by cdandrea** [comment]
@Nness this is great news. You'll be making a lot of people happy. I guess the potential is for this to fix some other sites we were attempting to have as Extension Menus. Thanks for tackling this one 👍

**Comment by Nness** [comment]
Electron been upgraded, it is under release schedule. 
* 30th of Sep: AU
* 5th of Oct: Rest of world.
