### ISSUE TITLE
DeskDirector: Quick Click End-User contact tickets

### ISSUE THREAD

**Issue by dustinabingham** [DeskDirector/Issues#187]
Hello,

I haven't been using Desk Director long, but I wanted to contribute and request a feature that I think is possible for the platform as it's already partially there. So currently, within your ticket list view, you can click on a company or tech and auto filter to those tickets; excellent feature! It's fast and convenient! But what about adding being able to select the contact/end-users name in the view list as well and it filters quickly to all of that user's tickets? Is this possible?

Thanks!

**Comment by DDAndyChen** [comment]
Hi dustinabingham,
Please contact support@deskdirector.com to report an issue.
This issue will be closed automatically.
Regards,
Deskdirector
