### ISSUE TITLE
DD: Contact CC's in Tech Tickets

### ISSUE THREAD

**Issue by dustinabingham** [DeskDirector/Issues#188]
Hello,

Is it possible that tickets can reflect the CC'd emails added by end-users via email submitted tickets? If an end-user is bringing in their own clients to get assistance or someone outside their normal email domain, it can be problematic and cause a loss of communication when we attempt a return response.

Does this make sense?

**Comment by DDAndyChen** [comment]
Hi dustinabingham,
Please contact support@deskdirector.com to report an issue.
This issue will be closed automatically.
Regards,
Deskdirector
