### ISSUE TITLE
[10818, 10641] The country code on the "Call me Back" screen is incorrect.

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#19]
The country code on the "Call me Back" screen is set to "New Zealand (+64)" even though it is configured to another country code inside the Admin Console.

**Comment by chris-ls** [comment]
This was hardcoded to NZ during initial development, when we did not have this API.

**Comment by chris-ls** [comment]
This issue has been resolved in current development code, but has yet to be released.
Plan released date is the week ending July 20th 2018.

**Comment by chris-ls** [comment]
@FluidNets-DamianS

**Comment by Nness** [comment]
Damian reported that windows app works correctly but web.

@chris-ls can we confirm this has been fixed for both windows app and web.

**Comment by chris-ls** [comment]
@Nness I couldn't reproduce 'that it works' on the desktop app.
That change has not yet been released.

Regardless, this code will be part of the release for this week.

**Comment by chris-ls** [comment]
Fixed in Portal Web/v2.18.11 - Released 23/07/18
Fixed in Portal Desktop/v1.74.0 - Released 24/07/18
