### ISSUE TITLE
[22961] Favicon does not reflect branding

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#196]
The mvc/File/Ico path returns the global branding. Best solution will be to refactor the Portal logic so that it retrieves the assets from the branding apis, and then sets the favicon.

**Comment by Nness** [comment]
This is done at server side, which will be release to test environment this week. Expected public release is on 20th of July for all regions.

**Comment by Andrew-Lahikainen** [comment]
@Nness thanks!
