### ISSUE TITLE
Saving a section redirects to base section instead of showing new section (and fields) added

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#200]
Each time a new section is added/edited, once you save the new section, it redirects to the Base Section instead of showing the newly credited/edited section (and its fields).

Screen recording for reference:
![AdditionalSection](https://user-images.githubusercontent.com/13637718/98290590-c021be80-200e-11eb-9557-28abaa223de6.gif)

**Comment by Nness** [comment]
I will see what I can do with this, it can also resolve the other issue you created. 

Currently system doesn't have draft,  so empty section will be removed up on save. So, even if UI didn't reset up on save in the future, the empty section will be gone if you navigate away.

**Comment by Nness** [comment]
addressed with 1.18.5
