### ISSUE TITLE
Adding a new section to a form, but not adding a field does not save new section added

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#201]
When adding a new Section to a form and you click "Save" without adding a field, it does not save the new section.

There is no warning/error too that the section will not be saved without a field added.

Screen recording for reference:
![AdditionalSectionIssue](https://user-images.githubusercontent.com/13637718/98291241-afbe1380-200f-11eb-888e-387db5fa84e1.gif)

**Comment by Nness** [comment]
Empty section is not allowed.
