### ISSUE TITLE
[23974] Date Picker not working on Safari

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#202]
Client has reported that the datepicker field does not work on a Safari 14.0 running on macOS 10.15.7.  The field appears as empty (instead of having dd/mm/yyyy pre-filled) and the datepicker does not appear when clicking the field.

**On Safari** (not working):
![image](https://user-images.githubusercontent.com/13637718/99199209-5ff6fd80-2802-11eb-8f10-c64b45da9e0d.png)

**On another browser** (working):
![image (1)](https://user-images.githubusercontent.com/13637718/99199213-66857500-2802-11eb-86ec-d1ba964e13c8.png)

Also tested it on a Safari 12.0 running on MacOS 10.14 from my end and I see the issue as well.

**Comment by Nness** [comment]
Addressed in portal release 3.15.1.

In the near future, Safari's date field will be fixed, we will switch back to normal date select field early next year.
