### ISSUE TITLE
[24015] When creating a macro, the second identical token does not populate.

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#203]
When creating a macro that uses the same token more than once, the second token does not populate.

Here is a screenshot of a sample macro that uses `{{contact.name.name}}` twice:
![Screenshot 2020-11-18 090241](https://user-images.githubusercontent.com/13637718/99441802-462df580-297d-11eb-9917-7b6d9abd3dd2.png)

Here's a screen recording showing the macro tested. It shows it populates `Kenny Dalglish` on the first variable, but only appears as `{{contact.name.name}}` on the second identical token.
![Macro](https://user-images.githubusercontent.com/13637718/99441811-4af2a980-297d-11eb-9024-9b4b48599c68.gif)

**Comment by Nness** [comment]
It has been fixed in TECH portal release 1.31.3. 

Same release also come with advanced token recognition system. Where it is no longer case sensitive, and can have suffix or prefix spaces. e.g. {{ Contact.NAME }} should now working same as {{contact.name}}
