### ISSUE TITLE
[24035] Macros not populating if there is no token in it

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#204]
If a macro only has plain text, it will not show up if you add it to a ticket. It only populates if the macro has a token being called in it.

Screengrab to better explain the issue:
Macro WITH a token - works
Macro without Token - does not work

![MacroBug](https://user-images.githubusercontent.com/13637718/99584473-dfc2d900-2a49-11eb-84e8-ed427644d5d0.gif)

**Comment by Nness** [comment]
Fixed in release 1.31.4. Should be available 15~20 min within this post.
