### ISSUE TITLE
[24146] Chat Subject Runoff

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#206]
**ISSUE:**
Users submitting chat requests can write a large amount of text in their issue box prior to submitting a request for chat. With this, once a chat request is initiated, if the text is too long, the text is cut off & custs are unable to read the full request. From there the technician has to ask for clarifying data ,or can then see the full length of the subject once the chat is converted to a ticket.

**Expected Behavior**
Either limit the characters for initial text to fit limits of the chat subject, or add their problem to the first initial message sent for the chat session to be able to gather their data.

**Screenshots/grab:**
https://drive.google.com/file/d/1ZE3qcnIEUJY3LARnYb7Gq8XAUlJw0Vwd/view?usp=sharing

**Link to ticket:**
https://support.deskdirector.com/tech/tickets/24146/details

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/103949250-d8918f00-519f-11eb-8109-dcea5ba18f37.png)

![image](https://user-images.githubusercontent.com/1712143/103949276-e515e780-519f-11eb-86f2-efe09452a7e7.png)

Two different project contribute to this issue.
- **Portal**: Portal use user message as ticket title. This can be lengthy.
- **Portal**: Ticketless chat should be ticketless, (a bit off topic)
- **TECH**: Need a different way to display ticket title. e.g. display ticket title as a system info block within chat window.

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/103949673-80a75800-51a0-11eb-893e-919a1c2ab451.png)
Portal's issue.

**Comment by Nness** [comment]
This has been resolved in latest TECH portal release.

* There is tooltip now when mouse over the chat window header.
* If the chat session title is not system generated, it display as chat message within chat window.
