### ISSUE TITLE
[24342] Type and Sub Type not in right order when creating a new ticket from TECH

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#207]
**Issue:**
When creating a ticket from the TECH portal, the Type and Subtype are not ordered in alphanumeric order just like how it looks in the Ticket Details section. Here's a screenshot of the Type dropdown when creating a ticket from TECH (https://support.forward-edge.net/tech/tickets/create)
![image](https://user-images.githubusercontent.com/13637718/103962227-5b741300-51bb-11eb-8170-0fbdbeb4a911.png)

I also checked the admin console and the ordering is also not following alphanumeric ordering.
![image](https://user-images.githubusercontent.com/13637718/103962636-4a77d180-51bc-11eb-90e0-9f44791e9398.png)

**Expected Behavior:**
Ticket type order should follow on Tech Details screen, alphanumeric order
Here's a screenshot of the Type dropdown when a ticket is open (e.g. https://support.forward-edge.net/tech/tickets/41710/details):
![image](https://user-images.githubusercontent.com/13637718/103962261-721a6a00-51bb-11eb-94b9-2cb065883116.png)

**Steps to reproduce the problem**
- Go to DD Tech Portal
- Click on new Ticket button in top middle
- Fill out ticket information, under details click on Type dropdown

**Links:**
https://support.deskdirector.com/tech/tickets/24342/details

**Comment by Nness** [comment]
This has been addressed in latest TECH portal release.
