### ISSUE TITLE
"Eye" icon in Request Type not linking to form editor

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#208]
Issue:
When editing a request type, under the GENERAL tab, when you click on the "eye" icon in **Form**, it will redirect to the Forms page, not the editor page of the specific form attached.

As I checked, the "eye" icon links to https://support.deskdirector.com/admin/v2/system/forms/xxx/editor while the new forms editor URL format is now https://support.deskdirector.com/admin/v2/portal/forms/xxxx/editor

**Comment by Nness** [comment]
This has been fixed at server side and admin console. Whichever release first should cover this case.

Server version 19.8.1

Earliest deploy schedule.
* 20th of Jan to AU
* 25th of Jan to US, EU, CA.


Latest deploy schedule:
1 week later than earliest deploy schedule.
