### ISSUE TITLE
[24507] Number field validation not working on Safari

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#209]
Issue:
Even with input validation enabled, letters can still be entered into a number field on a Request Type/Form.

Issue is only happening on Safari. Works fine on browsers like Chrome, Edge and Firefox

Here's a screenshot showing the issue on Safari. I am using Safari 14.0.2 on MacOS Big Sur when I replicated the issue
<img width="763" alt="Screen Shot 2021-02-03 at 6 03 13 PM" src="https://user-images.githubusercontent.com/13637718/106700833-816dc580-664a-11eb-9359-59fc87dd1ec7.png">

**Comment by Nness** [comment]
This won't be addressed until whole portal rewrite by using different JS framework. It is also not an issue, this is not number. If field is required then it should throw error.
