### ISSUE TITLE
[24515] Dash accepted on number field invalidates input

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#210]
**Issue:**
The number field on forms accepts a max of 2 dashes (-) as input, but it looks like this invalidates the number entered.

Here is a GIF showing the actual behavior
![NumberValidationDash](https://user-images.githubusercontent.com/13637718/106818178-d0fcd180-66dc-11eb-8637-2f3562f1bf24.gif)

**Observation:**
- When a number field is required, entering the dash between numbers invalidate the input as the "This field is required" message appears even if a number is still there. This behavior happens for both required fields with whole number validation and none.
- However, when the dashes are added before the numbers (negative number), works without any issues
**Input**
![image](https://user-images.githubusercontent.com/13637718/106818657-7617aa00-66dd-11eb-93cb-8a9bda34432c.png)

- On non-required fields, the number with dashes are taken (even with validation enabled), however, the numbers do not appear on the output

**Input:**
![image](https://user-images.githubusercontent.com/13637718/106818753-a0696780-66dd-11eb-9da2-deb5c87bf669.png)

**Form Output on Ticket:**
![image](https://user-images.githubusercontent.com/13637718/106819068-25548100-66de-11eb-975a-01c9a855159d.png)

This was tested on form https://dev.deskdirector.com/admin/v2/portal/forms/3623/editor

**Comment by Nness** [comment]
This won't be addressed until whole portal rewrite by using different JS framework. It is also not an issue, this is not number.
