### ISSUE TITLE
[24515] Number field not showing exact error when incorrect char has been input

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#211]
**Issue:**
The number field on forms accepts a max of 2 dashes (-) as input.  On non-required fields, there is no error that appears when number with dashes are entered. The form is submitted however, the input is not saved and the numbers do not appear on the output.

When a number field is required, entering the dash between numbers shows the error "This field is required" even if a number is still there. 

Here is a GIF showing the actual behavior
![NumberValidationDash](https://user-images.githubusercontent.com/13637718/106818178-d0fcd180-66dc-11eb-8637-2f3562f1bf24.gif)

**Input**
![image](https://user-images.githubusercontent.com/13637718/106818657-7617aa00-66dd-11eb-93cb-8a9bda34432c.png)

**Final Input:**
![image](https://user-images.githubusercontent.com/13637718/106818753-a0696780-66dd-11eb-9da2-deb5c87bf669.png)

**Form Output on Ticket:**
![image](https://user-images.githubusercontent.com/13637718/106819068-25548100-66de-11eb-975a-01c9a855159d.png)

This was tested on form https://dev.deskdirector.com/admin/v2/portal/forms/3623/editor

**Comment by iskolares** [comment]
Related to DeskDirector/Issues#209 and DeskDirector/Issues#210

**Comment by Nness** [comment]
The error should be correctly displayed on next client portal release.
