### ISSUE TITLE
Busy Status for Tech - DND new name for 'Busy' + make DND appear in drop down

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#212]
Issue 1. You cant see Busy in options for dropdown
![image](https://user-images.githubusercontent.com/7351746/109095737-30e91400-7781-11eb-9d98-23db880f7342.png)

![image](https://user-images.githubusercontent.com/7351746/109095820-5118d300-7781-11eb-9a1a-960e33b964e4.png)

**Comment by Nness** [comment]
This has been addressed in version 1.36.3 . also improved on version 1.36.4. Which whole panel been redesigned. 

Allow it to be shorter, much more compact without lose readability.


![image](https://user-images.githubusercontent.com/1712143/109718093-c2d2a000-7c0b-11eb-871b-cc7e941d9d97.png)
