### ISSUE TITLE
Service Radar buttons are opaque - should be solid 

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#216]
At some time in the last 3-4 months the coloring for data points for service radar has become opaque
the dots are really light, pastel colors. 
This makes them hard to see, particularly when a ticket is a region on its own 

They should strong primary colours.
![image](https://user-images.githubusercontent.com/7351746/118753884-fb545280-b8b9-11eb-93a9-782511d752e0.png)

**Comment by CharlesWarwick** [comment]
This is a better example. There are 6 tickets over 150 days old in this image 
![image](https://user-images.githubusercontent.com/7351746/118754099-6f8ef600-b8ba-11eb-88d9-2f085b831ff3.png)

**Comment by Nness** [comment]
It should now be addressed
