### ISSUE TITLE
Request Items can't be added in bulk

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#217]
When I page to a group of request type items & select them all to add to a request group the SAVE button doesn't not enable 
added request type items cannot be saved. 

https://user-images.githubusercontent.com/7351746/118967314-abab7f00-b9be-11eb-9df2-11aeb003071a.mp4

It may be because I am selecting/searching by category, I didn't get great repeatability 
But it did fail whenever I selected all items on a page

**Comment by CharlesWarwick** [comment]
When I only select 2 req types the problem disappears (see end of video) 

https://user-images.githubusercontent.com/7351746/118968047-8ec37b80-b9bf-11eb-8d9d-c5ec80d7faa5.mp4

**Comment by CharlesWarwick** [comment]
Failed to save with these 8 

https://user-images.githubusercontent.com/7351746/118968889-8ae42900-b9c0-11eb-8428-e80eb97c3b91.mp4

**Comment by Nness** [comment]
Request type group cannot have more than 100 items. This should be user voice for feature request. I don't think at this stage I would increase that threshold. It's not reasonable.

The total of request types you can have is 200 anyway, and you put 100 there without any kind of filtering.

**Comment by Nness** [comment]
![image](https://user-images.githubusercontent.com/1712143/119051639-89921b00-ba17-11eb-973f-097336c6d4e0.png)

Added error message. (10 is for testing, 100 is limit for live version).
