### ISSUE TITLE
Pressing ENTER when filtered to single selection should select that item

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#218]
e.g. If I filter to a single company and press ENTER then that company should be selected
Same with all tech searches. 

for example, If I press ENTER in the following image it should select DG Law
![image](https://user-images.githubusercontent.com/7351746/120312610-12208d80-c32d-11eb-981d-444c2bf36ae7.png)

Here's a video of the search:
https://user-images.githubusercontent.com/7351746/120312705-2d8b9880-c32d-11eb-9e91-2dd14c4aeecc.mp4

**Comment by Nness** [comment]
It is already the case right?
