### ISSUE TITLE
UnPin state should stick in DD Tech

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#219]
When I un-pin a tab to open a ticket in a new tab, the new tab should not be pinned 
i.e. the pinned state should persist until Pin is selected again 

https://user-images.githubusercontent.com/7351746/120313307-e225ba00-c32d-11eb-9ce0-a6ba04e7f6fb.mp4

**Comment by Nness** [comment]
1. That's not un-pin button but pin button
2. There won't be tabs in the future. It is something that will be removed.
