### ISSUE TITLE
New Ticket button on Company page

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#220]
IT would be helpful to create a ticket in Tech from the Company page
I will normally look to see if the ticket exists already so this is where I normally start a ticket in tech for a client 

![image](https://user-images.githubusercontent.com/7351746/120396108-221a8a80-c38a-11eb-9103-a928634a226b.png)

**Comment by Nness** [comment]
DeskDirector/UserVoice#563
