### ISSUE TITLE
Form improvement

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#221]
- [x] Improve on input error validation [not display correct error info](https://github.com/DeskDirector/Issues/issues/211)
- [x] Make required field more prompt
  - [x] Make submit button clickable to review problematic fields
  - [x] Mark previous fields as dirty when click on current fields.

**Comment by CharlesWarwick** [comment]
![image](https://user-images.githubusercontent.com/7351746/121010701-d6cd0580-c7e9-11eb-9d25-4b03e9527187.png)
Back and Next at the bottom of the form navigate from page to page

The Back action at the top of the form exits the Form completely 
![image](https://user-images.githubusercontent.com/7351746/121010785-f2381080-c7e9-11eb-88d7-ff3b89600306.png)

The behavior at top should match the bottom 
See this video for an other example


https://user-images.githubusercontent.com/7351746/121010884-11cf3900-c7ea-11eb-8e26-c1b4fd5f9ed9.mp4

**Comment by Nness** [comment]
@CharlesWarwick I don't think this is a major issue. Yes it is annoying, but it is also a learning curve. When back is present at top left position, the meaning is normally for breadcrumb.

We might improve the breadcrumb to make it more obvious, but the behaviour should be previoius page for form or not is questionable.

Also, the naming of next and back is misleading. It should be next and previous.


I cannot guarantee any change at this moment, some of small adjustment can do but it need an rewrite on the form to resolve many issues. Rename on button can be don't without rewrite, where top left link is independent from form.

This issue is long term issue, rewrite means component rewrite or portal rewrite.
