### ISSUE TITLE
New ticket state is triggering the CSAT survey to start 

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#222]
When I create a new ticket on [demosmp9](https://demomsp9.deskdirector.com/admin) the new state triggers the CSAT to show 

Changing the state (e.g. to 'In Progress') corrects, The example shown in the recording is supposed to be in 'Approval Required' 
- Not sure what is happening 
- It appeared 'about' the same time as Groups 
- It is not occurring on DD4DD

https://user-images.githubusercontent.com/7351746/121011487-c9644b00-c7ea-11eb-91d2-950020a88e65.mp4

**Comment by Nness** [comment]
@DDAndyChen could you double check status behaviour of Toki Iti?

**Comment by DDAndyChen** [comment]
this only happens to psa microsoft, the fix has been deployed to all demomsps now.
