### ISSUE TITLE
Temporary Full licenses - How many days left 

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#223]
The temporary license increase that we can make in the [Data Sync](https://techheads.deskdirector.com/admin/v2/configs/deskdirector-admin/data-sync) page fo the Portal is a great feature. Particularly when we are moving a customer from Chargify to Stripe. (e.g. Techheads below moving from Essentials to Gold ) 
What would be very helpful would be to know when the temporary license upgrade expires

![image](https://user-images.githubusercontent.com/7351746/121990014-37170500-cdf1-11eb-9ffb-d0956bdee188.png)

**Comment by Nness** [comment]
refer to [team communicatioin](https://teams.microsoft.com/l/message/19:840f6bd021144622989179225f97ccda@thread.skype/1623729940077?tenantId=342f0676-bb50-446a-bd9d-5d86f49e3696&groupId=fcc34222-82c5-4c75-96b6-97e737e74992&parentMessageId=1623729380962&teamName=Customer%20Success&channelName=Implementation&createdTime=1623729940077).
