### ISSUE TITLE
Can mouse-click select a user

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#224]
In Groups I can't mouse-click to select a user from the list
Pressing enter will work. I get the same behaviour in Edge & Chrome

https://user-images.githubusercontent.com/7351746/123947995-18ba2780-d9f5-11eb-9a6e-cb151193a0c8.mp4

**Comment by Nness** [comment]
Does keyboard working? e.g. up key, down key and enter.

**Comment by Nness** [comment]
Support on mouse click is coming. It was designed as keyboard in mind before.
