### ISSUE TITLE
[25581] Remove Impersonate button for Streamline IT

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#226]
Currently, for a StreamlineIT user, an impersonate button appears when on contacts page accessed from tickets. The button however does not work. 

When on the actual Contacts page, there is no impersonate option. Here are screenshots:

![Screen Shot 2021-07-14 at 9 40 54 AM](https://user-images.githubusercontent.com/13637718/125530882-09b140b3-57ea-4b6d-8a9a-73861dc0920a.png)

![Screen Shot 2021-07-14 at 9 40 38 AM](https://user-images.githubusercontent.com/13637718/125530890-1ea140b9-05c1-48b5-be34-895849371435.png)

**Comment by Nness** [comment]
removed button, fix should be deployed and available within 30 min. 

On its problematic page, it already has new impersonate button, thus, for this legacy button without checking member state should be removed.
