### ISSUE TITLE
Login dialogue throttling (disable password login)

### ISSUE THREAD

**Issue by CharlesWarwick** [DeskDirector/Issues#228]
test

**Comment by Nness** [comment]
They don't have to use password, other than password it is complete secure. Only password can brute force.

**Comment by Nness** [comment]
On the other hand our password requirement is based on better measurement. Event people want to brute force it will take a while. Our password setting prefer longer password. Not enforce complex but short password.

I'm not sure what kind of knowledge they have on login security, if they have concern they can ask me directly which I can explain.

**Comment by CharlesWarwick** [comment]
It was a BS vulnerability, but I still think its an issue that our login dialogue no throttling (but not urgent)
https://support.deskdirector.com/tech/tickets/26285/details
