### ISSUE TITLE
Missing CC Notification even for Autotask

### ISSUE THREAD

**Issue by iskolares** [DeskDirector/Issues#229]
There isn't a CC Notification email event for DD for Autotask. 

Here's the available events for DD Autotask:
![Screen Shot 2021-10-04 at 2 43 14 PM](https://user-images.githubusercontent.com/13637718/135782320-3f019457-4f7d-45f0-9dc4-0d1628134c74.png)

**Comment by Nness** [comment]
This has been adjusted and on admin portal's staging channel. It will be released next week on version 1.30
