### ISSUE TITLE
Avoid Aggressive Notifications and ConnectWise's "Send To" options.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/Issues#237]
Ticket Reference: Connectwise sending out emails 
https://support.deskdirector.com/tech/tickets/40042/details

We introduced some functionality to catch and suppress DeskDirector’s requests to ConnectWise that are email related.

With this feature enabled, the following checkboxes still trigger emails out of ConnectWise:

![image](https://user-images.githubusercontent.com/30588784/169167176-db8da050-74a1-4389-9a95-3cb87e4f8f13.png)

Creating an issue for consideration of extending this functionality to either:
* Ignore the flags if they're selected
* Hide these options in DD Tech from the UI

[Teams Discussion.](https://teams.microsoft.com/l/message/19:cc529377f7cd4f24be55a5a22b61f1a8@thread.skype/1650893318616?tenantId=342f0676-bb50-446a-bd9d-5d86f49e3696&groupId=3900a0d5-4aab-48d8-8d7d-3379765e8a65&parentMessageId=1650893318616&teamName=DeskDirector%20Support&channelName=Tickets&createdTime=1650893318616)

**Comment by DDAndyChen** [comment]
Hi Aycorn,
Please contact support@deskdirector.com to report an issue.
This issue will be closed automatically.
Regards,
Deskdirector

**Comment by Nness** [comment]
This has been addressed.
