### ISSUE TITLE
Dynamic Content rendering on form load rather than section load

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/Issues#238]
Example Ticket: https://support.deskdirector.com/tech/tickets/44041/details
Knowledge Base: https://help.deskdirector.com/article/b9l6cb0syu-desk-director-forms-dynamic-content

Q: Will dynamic content able to refresh based on the answer from other field?

A: No, not at moment. For now, you can put field ID within your API URL's query parameter, we will pass the value to your API at the time of rendering. Thus, content based on previous section is the way to go.

Comment from Jason:

"the content is loaded when form has been loaded. this is an issue, but I don't have any estimate when when that can be resolved or whether we can resolve until we rewrite portal"

**Comment by Nness** [comment]
- [x] Content should now only load when section been accessed.
- [x] Content should reload if navigate to other section then navigate back
- [x] If field from previous section and id been specified in content API URL's query parameter. The UI will pass the result of those field to the API.

It is available in latest client portal release. 3.31.1
