### ISSUE TITLE
[10786] Portal Office Hours sometimes reports "Out of Hours" when it is really inside office hours.

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#24]

**Comment by Nness** [comment]
Do we know the reason behind this?

**Comment by chris-ls** [comment]
Have not confirmed the reason behind this yet, only reproduced the issue.

**Comment by chris-ls** [comment]
There was a secondary issue related to Office Hours:
The logic to return the 'Next Office Hours' sometimes returned the 'next-next' office hours.
e.g. Today is Wednesday after hours, the logic would return Fridays hours.
Today is Thursday morning before hours, the logic would return Thursday hours.

This has been resolved.

**Comment by chris-ls** [comment]
This issue was originally reported with an 'Out of office hours' notice displayed inside a chat-dialog.

Possible explanation for this:

There may have been a chat dialog that was not ended from the previous day.
The portal then launches _before_ the office hours for that day.

Currently when the chat-dialog is initialized, there is logic to push system messages to the dialog.
Since chat-dialog was initialized before 07:30AM, an out-of-hours system message would have been pushed.

These system messages currently don't 'dissapear' when the conditions for them originally being pushed, no longer hold.

**Comment by chris-ls** [comment]
Fixed issue relating to incorrect 'Next Office Hours' message.

Did not fix issue related to 'Out of office hours' message displayed inside the chat dialog.
This was believed to have occurred, due to the Portal initializing _before_ office hours that day, and pushing the 'out of hours' system message to a chat which was existing from the previous day.
This issue needs to be handled in a different way and will come down to how we manage chat-sessions which are no longer active.
The real issue is that the portal user should not have seen this chat-dialog in the first place (since any reasonable tech support would not leave a chat hanging there after everyone has gone home).
