### ISSUE TITLE
DD Tech | "Add Form" tab on Autotask instance has no action.

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/Issues#241]
Clicking the **Add Forms** tab on an Autotask customer's instance has no action.

![image](https://user-images.githubusercontent.com/30588784/207994594-0116244f-90d1-49ce-abc7-4cb5c1bc4431.png)

Sample taken from https://parasolalliance.deskdirector.com/tech/tickets/420313/details

**Comment by Nness** [comment]
fixed on CI/CD
