### ISSUE TITLE
Option to Print within customer portal hides at smaller resolutions

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/Issues#243]
While loaded into a ticket in the customer portal, the PRINT option is hidden at smaller resolutions.

![msedge_GKUhfEW2qk](https://github.com/DeskDirector/Issues/assets/30588784/82b830bf-d448-4c39-a671-b6eb3f0b14e7)

-----

Hidden at smaller resolutions is misleading term, correct way to describe is that print and chat option's visibility changed from depends on screen size to container size.

- screen size = the browser window size
- container size = ticket detail's parent element size

The latest change to portal is to make ticket detail depends on container size to ensure communication timeline's readability, which caused some of desktop functionality to be hidden under large screen (smaller container).

**Comment by Nness** [comment]
This has been fixed and CI/CD is on the way. Expect to be live within 2~3 hours.
