### ISSUE TITLE
[7630] Portal text input field not obvious

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#3]
![currentform](https://user-images.githubusercontent.com/1712143/41392800-f6e17dcc-6ff6-11e8-8d21-c44251a351be.png)

Portal use Google's material spec for text input, but that spec has been updated to resolve issue where user could not figure out it is for text input. We should adjust text input according to new spec.

![2018-06-14_17h33_04](https://user-images.githubusercontent.com/1712143/41393258-01972b7a-6ff9-11e8-8972-bcf0f192cf45.png)

**Comment by chris-ls** [comment]
Closing this issue since we have now deprecated this UI.
If you believe this issue still applies to the new Request Support User Interface, please feel free to submit a new ticket.
