### ISSUE TITLE
[11004] OAuth not working correctly in TECH

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#30]
Since moving TECH to the server route `/tech`, OAuth no longer works properly. TECH is giving the server the wrong redirect url, which is just the origin. The fix is to change this to origin + /tech

**Comment by Andrew-Lahikainen** [comment]
This fix has been merged in and is waiting on release.

**Comment by Andrew-Lahikainen** [comment]
Released in 1.6.0

**Comment by FluidNets-DamianS** [comment]
@Andrew-Lahikainen is this already released?  I do not see it as working.

**Comment by Andrew-Lahikainen** [comment]
@FluidNets-DamianS I pushed out a fix for that, refresh and try again now. Cheers!

**Comment by FluidNets-DamianS** [comment]
MS Login is working again.
