### ISSUE TITLE
[10950, 11053, 21001] Logo backgrounds in Portal are inconsistent when "Dark Side Nav" theming is enabled

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#31]
There are currently two places that the branding Logo is shown inside the Portal.

1. The login dialog
2. Top of the Side Navigation

Turning on the "Dark Side Nav" theming option, turns the side navigation dark, but not the login dialog.
This creates an issue for logos that were optimized to show on either of the dark/light backgrounds.

An example of this, is a logo with a transparent background, containing white text

Side Navigation:
![chrome_2018-08-02_11-03-17](https://user-images.githubusercontent.com/5317900/43553678-40a4ec6e-9644-11e8-8267-9cc947b81f25.png)

Login Dialog:
![chrome_2018-08-02_11-02-55](https://user-images.githubusercontent.com/5317900/43553684-474d112c-9644-11e8-835a-bd107e7dcf8f.png)

**Comment by chris-ls** [comment]
This inconsistency restricts the designs of logos that can be used, as they have to simultaneously look good on both light/dark backgrounds.

It is also unexpected behavior, as when our customers are checking that their logos look good, they may only check what it looks like in the Side Nav (especially if they are already logged into the Portal, they might never see the login dialog)

**Comment by chris-ls** [comment]
Possible solution:

The login dialog will also turn dark when the "Dark Side Nav" setting is enabled.
This will involve changing the name of this setting as it affects more than the Side Nav.
The login dialog will need some work done to make sure it looks good with a dark theme.

**Comment by AirLHull** [comment]
Good idea,  we are able to alter our logo as currently its Orange to ensure consistency across both pages. Providing an option that will allow us to "Switch" the options on and off should prove beneficial.

**Comment by Andrew-Lahikainen** [comment]
Fixed in Portal 3.9.0

The login form now uses a dark background so that logos will stand out better.
