### ISSUE TITLE
[11055, 11084] Request Type breadcrumbs show a TypeId number at the end rather than their name

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#34]
![new_support_system_confusion](https://user-images.githubusercontent.com/5317900/43750159-2e133f28-9a4b-11e8-92a8-fc7438397b6f.png)

**Comment by Andrew-Lahikainen** [comment]
This has been implemented and is waiting on deploy.

**Comment by chris-ls** [comment]
Deployed with Portal Web/v2.19.6 on 06/09/18

**Comment by chris-ls** [comment]
Deployed with Portal Desktop/v1.79.0 on 14/09/18
