### ISSUE TITLE
[10955] Clicking on link to download Quote PDF inside Quosal quote crashes Desktop Portal

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#38]

**Comment by bobsquid** [comment]
Has there been any progress on this issue?  I am waiting to roll the quosal approval functionality out to clients, but I can't do that until this part is working.

**Comment by chris-ls** [comment]
@bobsquid 

There will be a fix for this issue shipping in the next release, early next week (most likely Monday).

This took longer than expected to resolve since the core issue lay inside Electron (the desktop framework we use) and the primary alternative implementation also had issues related to Electron :(

We've managed to work around these now though.
There will be a slight change to the layout of the Quote view.
Instead of opening a dialog to display the quote, we will now display the quote full-size with a breadcrumb type navigation.
Overall I think this will be an improvement to the UI/UX of this view anyway

**Comment by bobsquid** [comment]
Thanks for the update Chris, I'll keep an eye out for it next week!

**Comment by chris-ls** [comment]
Released with Portal Desktop/v1.81 on 09-Oct-2018.

**Comment by bobsquid** [comment]
Thanks Chris.  My portal says "Version 1.80.0 Up-to-Date!", do I have to manually download and push the updated portal to all of my users for them to get the new version?

**Comment by chris-ls** [comment]
@bobsquid We are experiencing some issues with the code that builds out the updated msi's/exes for everyone, so v1.81 didn't get rolled out properly.
I just pushed your build through so you are on v1.81 now.
Your clients should automatically update to this version after a short time.

**Comment by bobsquid** [comment]
Thanks, it works now (and I like the new look of the quote section)!

Do you have an estimate of how long it will take to update my clients?  Should I be expecting this week, or next?

**Comment by chris-ls** [comment]
@bobsquid Ideally the update should take on the order of hours.

Each client checks for updates periodically (every hour).
Once the update is downloaded it will wait until the user isn't using the app (minimized, or hidden in task bar) before updating and restarting.

**Comment by bobsquid** [comment]
@chris-ls - I've been randomly checking a few clients' machines over the past week or so, and none of the ones I've looked at have been updated to v.1.81 yet.  Is there something I need to do on my end to speed this up?

**Comment by chris-ls** [comment]
@bobsquid Just checking to see if you received my reply on ticket #12207 ?
