### ISSUE TITLE
[11776, 11514] Tickets created via. WufooForm do not attach CW Configurations

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#48]
This affects only the installed Desktop Portal when PortalV2 is enabled.

**Comment by chris-ls** [comment]
Fixed and will be deployed in the next release cycle ~24th September

**Comment by djgmog** [comment]
What needs to be done for us to test this fix today?

**Comment by chris-ls** [comment]
@djgmog 
v1.80 is rolling out now, which contains a fix for this.
Ensure that you are using v1.80 when testing by downloading the latest exe from your Admin Console and installing.
To confirm this has fixed your particular issue, create a ticket from the desktop client via. wufoo-form request type.

**Comment by chris-ls** [comment]
Deployed to Portal Desktop/v1.80 on 26-Sep-2018
