### ISSUE TITLE
[10213] Screen stretches and uses a lot of cpu when moving desktop app window

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#5]
This only happens under certain conditions:
* if the app is moved between monitors of different resolutions
* if the app is moved around with scaling enabled

This is related to a feature that was never publicly released; [multi-user desktop logins](https://github.com/DeskDirector/UserVoice/issues/10). We are likely going to remove this feature which will resolve this issue.

**Comment by chris-ls** [comment]
This issue has been resolved.
This will be deployed with Portal Desktop v1.77

**Comment by chris-ls** [comment]
Deployed with Portal Desktop v1.78 on 24/08/18
