### ISSUE TITLE
[11865] Cannot sign in as another user when active-directory login is configured

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#52]
Cannot sign in to the Portal as a different user, when ActiveDirectory automatic login has been configured for the Windows user who is signed in.
The ActiveDirectory automatic login overrides any manual login attempts.

**Comment by AirLHull** [comment]
Hi Guys, any luck on this?

**Comment by chris-ls** [comment]
@AirLHull 
Work hasn't started on this issue yet.
This is currently scheduled for the first week of November as we push through other work.

**Comment by chris-ls** [comment]
A fix for this issue will be deployed next Monday Nov-12-2018

Current behavior:
Whenever ActiveDirectory has been set up for a user, the user will be logged in as the ActiveDirectory user in all cases.
It is not possible to log in as another user when ActiveDirectory has been configured for the user account.

New behavior:
Whenever ActiveDirectory has been set up for a user, the user will be logged in as the ActiveDirectory user, if and only if, they are not already authenticated with DD as another user.
This means that on first start, a user should be logged in as their ActiveDirectory user by default.
If the user logs out and then logs in as another user, they will remain logged in as that user even after restart/reinstall.
The only way to get the ActiveDirectory user to log back in, will be to manually log out, then restart the app.

**Comment by chris-ls** [comment]
Fixed and deployed with PortalDesktop/v1.84 on 13-Nov-2018

**Comment by chris-ls** [comment]
Reopening this due to an issue with the implementation.
Clicking "Log Out" from the Portal currently re-loads the application in addition to sending the user to the login page.

This application re-load triggers the active-directory re-authentication (since we attempt to perform AD auth on application load)

**Comment by chris-ls** [comment]
A fix for this was released for PortalDesktop/v1.89.0 on 12-December-2018

Active Directory authentication will now only occur on the desktop client "Loading screen".
This will enable you to sign out of the Portal and sign in as someone else, without it being overridden by the AD authentication immediately.

* Note that when the application restarts, the Portal will re-authenticate with the AD user found on the system.
This is by design, as we need to regularly re-authenticate AD users, so that they don't get sent to the login screen after their cookie expires in 30 days time.
