### ISSUE TITLE
[12426] BiggerBrains content does not load correctly in certain situations

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#60]
Certain bigger brains courses fail to display correctly, when rendered by the DD Media Server.
This issue shows up when there is even a small amount of network delay with fetching the content.

**Comment by Lowell-Syncrety** [comment]
So far every course I've tried is like this; the "Next" or "Continue" button is about 5-6 screens down, so end-users have to scroll all the way to the bottom every time whether to check an answer or click next.  It's stopped my rolling out of Bigger Brains to customers as this makes it difficult for folks to use.

**Comment by chris-ls** [comment]
@Lowell-Syncrety 
Will be taking a closer look at this shortly.
The issue is related to some iframe resizing logic, which isn't playing well with Thinkific.

We could only reproduce the issue on our side by throttling our network speed, which suggests it is an issue related to the loading order of the content.

We will keep this post updated.

**Comment by Lowell-Syncrety** [comment]
Thanks, @chris-ls.  On our side it is consistent, always happens.  Tried on 2 computers, both on different firewalls, but on the same 300/300Mbit fibre connection.  But tried again today, and so far it's working well.  Interesting.

**Comment by chris-ls** [comment]
@Lowell-Syncrety 
Yeah this is common for issues involving asynchronous execution of code, different outcomes on different days, even with the same starting conditions.

We already know the changes that need to be made, but there is just a few issues holding us back, which should be resolved shortly.

**Comment by chris-ls** [comment]
This issue should be fixed now.
All content should automatically take the full available view-height allocated to it.

Also removed the "blank space" that appears at the bottom of learning items.

If there are any other issues encountered with BiggerBrains or other content, please feel free to open another ticket and we will address that.

**Comment by Lowell-Syncrety** [comment]
Thanks much!  I've been sporadically testing over the last couple weeks and haven't seen the issue show up anymore.
