### ISSUE TITLE
[12220] Ticket-list UI requires UX improvement

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#66]
Currently the ticket-list UI does not differentiate between a "loading state" and an "empty state".
On slower connections, this creates a very sub-par experience.

Combining this with the fact that there is no way to refresh the ticket list, except to navigate between different states (i.e. Open Tickets -> Closed Tickets -> Open Tickets just to refresh the open tickets),
this can create a frustrating experience for the users.

Some users have also reported that clicking on a ticket in the ticket-list will sometimes take them to a different ticket (usually the one positioned above)

**Comment by Andrew-Lahikainen** [comment]
Fixed in tickets-v2
