### ISSUE TITLE
[12762] Cannot switch between Wufoo Forms in the same Category

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#67]
This issue affects the older "Dropdown" support screen.
Users are unable to switch between different Wufoo Forms that exist inside the same Category.

**Comment by chris-ls** [comment]
Fix released to Portal Web/v2.20.13 on November-22-2018

Will be released to Portal Desktop week beginning November-26-2018

**Comment by AirLHull** [comment]
If you can let me know once it has been released for Desktop that would be great!

**Comment by chris-ls** [comment]
@AirLHull Just releasing this now.
You should receive an email after I close this issue :)

**Comment by chris-ls** [comment]
Released to Portal Desktop/v1.88.0 on November-28-2018
