### ISSUE TITLE
Portal mobile UI/UX needs improvement

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#74]
There are a few places where the UI/UX of the web version could be improved on mobile devices.
Any substandard UI/UX should be recorded and addressed here.

**Comment by chris-ls** [comment]
The text inside the Request support options does not wrap correctly:
![image](https://user-images.githubusercontent.com/5317900/51347761-db53cf00-1b05-11e9-9a1f-4e3e523031d1.png)

**Comment by chris-ls** [comment]
Ticket title doesn't fully display at the top of a ticket-timeline panel
![image](https://user-images.githubusercontent.com/5317900/51347865-2372f180-1b06-11e9-969d-5c76ac220965.png)

**Comment by chris-ls** [comment]
Technician avatars overflow ticket information inside the ticket-details panel
![image](https://user-images.githubusercontent.com/5317900/51347974-5fa65200-1b06-11e9-8525-85af370f333c.png)

**Comment by Andrew-Lahikainen** [comment]
All responsive design efforts will be put into the new tickets ui v2
