### ISSUE TITLE
[13623] Auto approved note been added when status is approve granted status

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#76]
Auto approved note currently been added when status is equal to approve granted status, in some circumstances. where customer have same status for new and approval granted, this note will be added regardless of what actually happened.

Our code should aware of auto approve action instead of using status to determine.

**Comment by Nness** [comment]
@DDAndyChen could you resolve this for this week's server release? This include 2 CW implementations, SOAP and RESTful. Also check Autotask see if have similar case.

**Comment by DDAndyChen** [comment]
This has been released.
