### ISSUE TITLE
Clear All / Scoll Bar for DD Tech Tickets

### ISSUE THREAD

**Issue by Aycorn** [DeskDirector/Issues#81]
![image](https://user-images.githubusercontent.com/30588784/54503691-274fb280-4995-11e9-805a-7d2cf5928ed9.png)

Current issue with too many tickets tabs open.

**Comment by Andrew-Lahikainen** [comment]
Scrolling will probably be best

**Comment by Nness** [comment]
This is no longer an issue, as we now have tab limit and pin tab mechanism.
