### ISSUE TITLE
[14588, 15051] Avatars not rendered consistently inside Portal

### ISSUE THREAD

**Issue by chris-ls** [DeskDirector/Issues#82]
* Avatars look a bit blurry inside the ticket timeline. This is due to using quite a low resolution here. This can be increased.
* Avatars don't retain the correct aspect ratio inside of the ticket details panel. Here they are forced to be square and don't focus in on the persons face.

**Comment by Andrew-Lahikainen** [comment]
Additionally raised on ticket 15051

**Comment by Andrew-Lahikainen** [comment]
Fixed in tickets-v2
