### ISSUE TITLE
[18712] Chat is not abandoned if the user closes the browser before the chat can be handled

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#96]
To reproduce:

* Request a chat
* Do not answer through Tech
* Close browser window
* Answer chat request through Tech

Expected behaviour would be to abandon the chat request. Perhaps we can prompt an alert to get the user to confirm they want to abandon chat request.

**Comment by Nness** [comment]
We should just allow user free to join, free to leave.
